# Usa la imagen oficial de MySQL desde Docker Hub
FROM mysql:latest

# Variables de entorno para la configuración de MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=app_licores

# Copia los scripts SQL de inicialización al contenedor
COPY *_licores.sql /docker-entrypoint-initdb.d/

# Expone el puerto 3306 para permitir conexiones externas
EXPOSE 3306

# Comando para iniciar el servidor MySQL
CMD ["mysqld"]